<?php

class Colorlib_Walker_Nav_Menu extends  Walker_Nav_Menu{


    public function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0)
    {
        parent::start_el($output, $item, $depth, $args, $id); // TODO: Change the autogenerated stub
    }

    public function start_lvl(&$output, $depth = 0, $args = array())
    {
        parent::start_lvl($output, $depth, $args); // TODO: Change the autogenerated stub
    }

    public function end_lvl(&$output, $depth = 0, $args = array())
    {
        parent::end_lvl($output, $depth, $args); // TODO: Change the autogenerated stub
    }

    public function end_el(&$output, $item, $depth = 0, $args = array())
    {
        parent::end_el($output, $item, $depth, $args); // TODO: Change the autogenerated stub
    }


}